const countries = [
  { name: "afeganistão", code: "af" },
  { name: "áfrica do sul", code: "za" },
  { name: "albânia", code: "al" },
  { name: "alemanha", code: "de" },
  { name: "andorra", code: "ad" },
  { name: "angola", code: "ao" },
  { name: "antígua e barbuda", code: "ag" },
  { name: "arábia saudita", code: "sa" },
  { name: "argélia", code: "dz" },
  { name: "argentina", code: "ar" },
  { name: "armênia", code: "am" },
  { name: "austrália", code: "au" },
  { name: "áustria", code: "at" },
  { name: "azerbaijão", code: "az" },
  { name: "bahamas", code: "bs" },
  { name: "bahrein", code: "bh" },
  { name: "bangladesh", code: "bd" },
  { name: "barbados", code: "bb" },
  { name: "belarus", code: "by" },
  { name: "bélgica", code: "be" },
  { name: "belize", code: "bz" },
  { name: "benim", code: "bj" },
  { name: "butão", code: "bt" },
  { name: "bolívia", code: "bo" },
  { name: "bósnia e herzegovina", code: "ba" },
  { name: "botsuana", code: "bw" },
  { name: "brasil", code: "br" },
  { name: "brunei", code: "bn" },
  { name: "bulgária", code: "bg" },
  { name: "burkina faso", code: "bf" },
  { name: "burundi", code: "bi" },
  { name: "cabo verde", code: "cv" },
  { name: "camarões", code: "cm" },
  { name: "camboja", code: "kh" },
  { name: "canadá", code: "ca" },
  { name: "catar", code: "qa" },
  { name: "cazaquistão", code: "kz" },
  { name: "chade", code: "td" },
  { name: "chile", code: "cl" },
  { name: "china", code: "cn" },
  { name: "chipre", code: "cy" },
  { name: "colômbia", code: "co" },
  { name: "comores", code: "km" },
  { name: "congo", code: "cg" },
  { name: "coreia do norte", code: "kp" },
  { name: "coreia do sul", code: "kr" },
  { name: "costa do marfim", code: "ci" },
  { name: "costa rica", code: "cr" },
  { name: "croácia", code: "hr" },
  { name: "cuba", code: "cu" },
  { name: "dinamarca", code: "dk" },
  { name: "djibuti", code: "dj" },
  { name: "dominica", code: "dm" },
  { name: "egito", code: "eg" },
  { name: "el salvador", code: "sv" },
  { name: "emirados árabes unidos", code: "ae" },
  { name: "equador", code: "ec" },
  { name: "eritreia", code: "er" },
  { name: "eslováquia", code: "sk" },
  { name: "eslovênia", code: "si" },
  { name: "espanha", code: "es" },
  { name: "essuatíni", code: "sz" },
  { name: "estados unidos", code: "us" },
  { name: "estônia", code: "ee" },
  { name: "etiopia", code: "et" },
  { name: "fiji", code: "fj" },
  { name: "filipinas", code: "ph" },
  { name: "finlândia", code: "fi" },
  { name: "frança", code: "fr" },
  { name: "gabão", code: "ga" },
  { name: "gâmbia", code: "gm" },
  { name: "gana", code: "gh" },
  { name: "geórgia", code: "ge" },
  { name: "granada", code: "gd" },
  { name: "grécia", code: "gr" },
  { name: "guatemala", code: "gt" },
  { name: "guiana", code: "gy" },
  { name: "guiné", code: "gn" },
  { name: "guiné-bissau", code: "gw" },
  { name: "guiné equatorial", code: "gq" },
  { name: "haiti", code: "ht" },
  { name: "honduras", code: "hn" },
  { name: "hungria", code: "hu" },
  { name: "iemen", code: "ye" },
  { name: "ilhas marshall", code: "mh" },
  { name: "ilhas salomão", code: "sb" },
  { name: "índia", code: "in" },
  { name: "indonésia", code: "id" },
  { name: "irã", code: "ir" },
  { name: "iraque", code: "iq" },
  { name: "irlanda", code: "ie" },
  { name: "islândia", code: "is" },
  { name: "israel", code: "il" },
  { name: "itália", code: "it" },
  { name: "jamaica", code: "jm" },
  { name: "japão", code: "jp" },
  { name: "jordânia", code: "jo" },
  { name: "kiribati", code: "ki" },
  { name: "kuwait", code: "kw" },
  { name: "laos", code: "la" },
  { name: "lesoto", code: "ls" },
  { name: "letônia", code: "lv" },
  { name: "líbano", code: "lb" },
  { name: "libéria", code: "lr" },
  { name: "líbia", code: "ly" },
  { name: "liechtenstein", code: "li" },
  { name: "lituânia", code: "lt" },
  { name: "luxemburgo", code: "lu" },
  { name: "macedônia do norte", code: "mk" },
  { name: "madagascar", code: "mg" },
  { name: "malásia", code: "my" },
  { name: "malaui", code: "mw" },
  { name: "maldivas", code: "mv" },
  { name: "mali", code: "ml" },
  { name: "malta", code: "mt" },
  { name: "marrocos", code: "ma" },
  { name: "maurício", code: "mu" },
  { name: "mauritânia", code: "mr" },
  { name: "méxico", code: "mx" },
  { name: "micronésia", code: "fm" },
  { name: "moçambique", code: "mz" },
  { name: "moldávia", code: "md" },
  { name: "mônaco", code: "mc" },
  { name: "mongólia", code: "mn" },
  { name: "montenegro", code: "me" },
  { name: "mianmar", code: "mm" },
  { name: "namíbia", code: "na" },
  { name: "nauru", code: "nr" },
  { name: "nepal", code: "np" },
  { name: "níger", code: "ne" },
  { name: "nigéria", code: "ng" },
  { name: "nicarágua", code: "ni" },
  { name: "noruega", code: "no" },
  { name: "nova zelândia", code: "nz" },
  { name: "omã", code: "om" },
  { name: "palau", code: "pw" },
  { name: "palestina", code: "ps" },
  { name: "panamá", code: "pa" },
  { name: "papua-nova guiné", code: "pg" },
  { name: "paquistão", code: "pk" },
  { name: "paraguai", code: "py" },
  { name: "peru", code: "pe" },
  { name: "polônia", code: "pl" },
  { name: "portugal", code: "pt" },
  { name: "quênia", code: "ke" },
  { name: "quirguistão", code: "kg" },
  { name: "reino unido", code: "gb" },
  { name: "república centro-africana", code: "cf" },
  { name: "república democrática do congo", code: "cd" },
  { name: "república dominicana", code: "do" },
  { name: "república tcheca", code: "cz" },
  { name: "romênia", code: "ro" },
  { name: "ruanda", code: "rw" },
  { name: "rússia", code: "ru" },
  { name: "samoa", code: "ws" },
  { name: "santa lúcia", code: "lc" },
  { name: "são cristóvão e nevis", code: "kn" },
  { name: "são marino", code: "sm" },
  { name: "são tomé e príncipe", code: "st" },
  { name: "são vicente e granadinas", code: "vc" },
  { name: "seicheles", code: "sc" },
  { name: "senegal", code: "sn" },
  { name: "serra leoa", code: "sl" },
  { name: "sérvia", code: "rs" },
  { name: "singapura", code: "sg" },
  { name: "síria", code: "sy" },
  { name: "somália", code: "so" },
  { name: "sri lanka", code: "lk" },
  { name: "sudão", code: "sd" },
  { name: "sudão do sul", code: "ss" },
  { name: "suécia", code: "se" },
  { name: "suíça", code: "ch" },
  { name: "suriname", code: "sr" },
  { name: "tailândia", code: "th" },
  { name: "tajiquistão", code: "tj" },
  { name: "tanzânia", code: "tz" },
  { name: "timor-leste", code: "tl" },
  { name: "togo", code: "tg" },
  { name: "tonga", code: "to" },
  { name: "trindade e tobago", code: "tt" },
  { name: "tunísia", code: "tn" },
  { name: "turcomenistão", code: "tm" },
  { name: "turquia", code: "tr" },
  { name: "tuvalu", code: "tv" },
  { name: "ucrânia", code: "ua" },
  { name: "uganda", code: "ug" },
  { name: "uruguai", code: "uy" },
  { name: "uzbequistão", code: "uz" },
  { name: "vanuatu", code: "vu" },
  { name: "vaticano", code: "va" },
  { name: "venezuela", code: "ve" },
  { name: "vietnã", code: "vn" },
  { name: "zâmbia", code: "zm" },
  { name: "zimbábue", code: "zw" }
];